### ISSUE TITLE
Need to update composer-cli commands for new version

### ISSUE THREAD

**Issue by odrodrig** [IBM/BlockchainEvents-CompositeJourney#4]
In Step 2 the following needs to be changed:

Replace:
` composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName events`

 with 
` composer network install -a events.bna -c PeerAdmin@hlfv1`

And change:
` composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile events.bna --file networkadmin.card`

 To:
` composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --file networkadmin.card --networkName events -V 0.0.1`

**Comment by sanjay-saxena** [comment]
Resolved using the latest command-line switches/arguments supported by Hyperledger Composer 0.19.5.
