### ISSUE TITLE
Add extra bullet point in the composer-rest-server section

### ISSUE THREAD

**Issue by odrodrig** [IBM/BlockchainEvents-CompositeJourney#5]
In the section describing how to set up the composer-reset-server there are a series of bullet points that look like the following: 

-     Enter admin@events as the card name.
-     Select never use namespaces when asked whether to use namespaces in the generated API.
-     Select No when asked whether to secure the generated API.
-     Select Yes when asked whether to enable event publication.
-     Select No when asked whether to enable TLS security.

There needs to be an additional step after you enter No to secure the API. It should look like this:

-     Enter admin@events as the card name.
-     Select never use namespaces when asked whether to use namespaces in the generated API.
-     Select No when asked whether to secure the generated API.
-     Select No when asked about enabling Authentication with Passport.
-     Select Yes when asked whether to enable event publication.
-     Select No when asked whether to enable TLS security.

**Comment by sanjay-saxena** [comment]
Resolved by just putting in the output of the command directly in README.md.
